DELETE http://localhost:3003/api/blogs/60df74738157b01b1cdca0de
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhZW1pbiIsImlkIjoiNjBkZjcyMTc1MTc2ZGMyNTNjMDBhNjc1IiwiaWF0IjoxNjI1MjU3MjU0LCJleHAiOjE2MjUyNjA4NTR9.6sir-F0UgKgYSNSMNLSYppiYReusOZoB0CePOLLCfiY


